services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    volumes: 
      - wordpress:/var/www/html
    networks:
      - inception-network
    env_file:
      .env
    depends_on:
      - mariadb
    restart: always
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-network
    depends_on:
      - wordpress
    restart: always
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/inception/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/inception/data/wordpress
networks:
  inception-network:
    driver: bridge
