services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network
    #restart: always
    
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/repos/inception/data/mariadb
networks:
  inception-network:
    driver: bridge
